// productos.js - Inventario actualizado AME FIGURES
// Generado automáticamente desde la tabla proporcionada

const productos = [
    // ============================================
    // DRAGON BALL (DB_)
    // ============================================
    {
        id: 'DB_FIG_001',
        sku: 'DB_FIG_001',
        nombre: 'SON GOKU SUPER SAYAYIN',
        tamaño: '18 cm',
        precioOferta: 35,
        descuento: 20,
        precioInflado: 42.00,
        descripcion: 'Figura de Son Goku Super Saiyan de Dragon Ball - 18 cm.',
        palabrasClave: 'Dragon Ball, Goku, Super Saiyan, figura coleccionable, anime',
        categoria: 'Dragon Ball',
        pagina: 1,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874449/DB_FIG_001.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874448/DB_FIG_001_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874448/DB_FIG_001_2.png'
    },
    {
        id: 'DB_FIG_002',
        sku: 'DB_FIG_002',
        nombre: 'VEGITO SUPER SAIYAN BLUE',
        tamaño: '11 cm',
        precioOferta: 35,
        descuento: 30,
        precioInflado: 45.50,
        descripcion: 'Figura de Vegito Super Saiyan Blue de Dragon Ball - 11 cm.',
        palabrasClave: 'Dragon Ball, Vegito, Super Saiyan Blue, figura, colección',
        categoria: 'Dragon Ball',
        pagina: 2,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874448/DB_FIG_002.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874448/DB_FIG_002_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874447/DB_FIG_002_2.png'
    },
    {
        id: 'DB_FIG_003',
        sku: 'DB_FIG_003',
        nombre: 'ESCENA GOKU CAZANDO PESCADO',
        tamaño: '6.5 cm',
        precioOferta: 35,
        descuento: 40,
        precioInflado: 49.00,
        descripcion: 'Figura escena de Goku cazando pescado de Dragon Ball - 6.5 cm.',
        palabrasClave: 'Dragon Ball, Goku, escena, pescando, figura mini',
        categoria: 'Dragon Ball',
        pagina: 3,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874448/DB_FIG_003.png'
    },
    {
        id: 'DB_FIG_004',
        sku: 'DB_FIG_004',
        nombre: 'TRUNKS',
        tamaño: '19 cm',
        precioOferta: 39,
        descuento: 50,
        precioInflado: 58.50,
        descripcion: 'Figura de Trunks de Dragon Ball - 19 cm.',
        palabrasClave: 'Dragon Ball, Trunks, figura de acción, coleccionable',
        categoria: 'Dragon Ball',
        pagina: 4,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1/MG2M6Rr8/DB-FIG-004.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1/LsKY9f0m/DB-FIG-004-1.png'
    },
    {
        id: 'DB_FIG_005',
        sku: 'DB_FIG_005',
        nombre: 'VEGETA Y FREEZER',
        tamaño: '10.5 cm',
        precioOferta: 39,
        descuento: 20,
        precioInflado: 46.80,
        descripcion: 'Figura de Vegeta y Freezer de Dragon Ball - 10.5 cm.',
        palabrasClave: 'Dragon Ball, Vegeta, Freezer, dupla, figura',
        categoria: 'Dragon Ball',
        pagina: 5,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874447/DB_FIG_005.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874406/DB_FIG_005_1.png'
    },
    {
        id: 'DB_FIG_006',
        sku: 'DB_FIG_006',
        nombre: 'GOKU BÁCULOS',
        tamaño: '20 cm',
        precioOferta: 39,
        descuento: 30,
        precioInflado: 50.70,
        descripcion: 'Figura de Goku con báculos de Dragon Ball - 20 cm.',
        palabrasClave: 'Dragon Ball, Goku, báculo, figura articulada',
        categoria: 'Dragon Ball',
        pagina: 6,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874405/DB_FIG_006.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874405/DB_FIG_006_1.png'
    },
    {
        id: 'DB_FIG_007',
        sku: 'DB_FIG_007',
        nombre: 'ANDROIDE N° 17',
        tamaño: '24 cm',
        precioOferta: 45,
        descuento: 40,
        precioInflado: 63.00,
        descripcion: 'Figura de Androide N° 17 de Dragon Ball - 24 cm.',
        palabrasClave: 'Dragon Ball, Androide 17, figura grande, colección',
        categoria: 'Dragon Ball',
        pagina: 7,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874405/DB_FIG_007.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874405/DB_FIG_007_1.png'
    },
    {
        id: 'DB_FIG_008',
        sku: 'DB_FIG_008',
        nombre: 'ANDROIDE N° 18',
        tamaño: '23 cm',
        precioOferta: 45,
        descuento: 50,
        precioInflado: 67.50,
        descripcion: 'Figura de Androide N° 18 de Dragon Ball - 23 cm.',
        palabrasClave: 'Dragon Ball, Androide 18, figura femenina, coleccionable',
        categoria: 'Dragon Ball',
        pagina: 8,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874404/DB_FIG_008.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874404/DB_FIG_008_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874404/DB_FIG_008_2.png'
    },
    {
        id: 'DB_FIG_009',
        sku: 'DB_FIG_009',
        nombre: 'BULMA',
        tamaño: '18 cm',
        precioOferta: 35,
        descuento: 20,
        precioInflado: 42.00,
        descripcion: 'Figura de Bulma de Dragon Ball - 18 cm.',
        palabrasClave: 'Dragon Ball, Bulma, figura, anime',
        categoria: 'Dragon Ball',
        pagina: 9,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874404/DB_FIG_009.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874403/DB_FIG_009_1.png '
    },
    {
        id: 'DB_FIG_010',
        sku: 'DB_FIG_010',
        nombre: 'MAESTRO ROSHI',
        tamaño: '10 cm',
        precioOferta: 30,
        descuento: 20,
        precioInflado: 36.00,
        descripcion: 'Figura de Maestro Roshi de Dragon Ball - 10 cm.',
        palabrasClave: 'Dragon Ball, Roshi, maestro, figura',
        categoria: 'Dragon Ball',
        pagina: 10,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874403/DB_FIG_010.png'
    },
    {
        id: 'DB_FIG_011',
        sku: 'DB_FIG_011',
        nombre: 'TRUNKS DEL FUTURO SUPER SAIYAN DAI-SAN DANKAI',
        tamaño: '27 cm',
        precioOferta: 55,
        descuento: 30,
        precioInflado: 71.50,
        descripcion: 'Figura de Trunks del Futuro Super Saiyan de Dragon Ball - 27 cm.',
        palabrasClave: 'Dragon Ball, Trunks del Futuro, Super Saiyan, figura grande',
        categoria: 'Dragon Ball',
        pagina: 11,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874403/DB_FIG_011.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874403/DB_FIG_011_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874403/DB_FIG_011_2.png'
    },
    {
        id: 'DB_FIG_012',
        sku: 'DB_FIG_012',
        nombre: 'KRILIN',
        tamaño: '16.5 cm',
        precioOferta: 35,
        descuento: 40,
        precioInflado: 49.00,
        descripcion: 'Figura de Krilin de Dragon Ball - 16.5 cm.',
        palabrasClave: 'Dragon Ball, Krilin, figura, coleccionable',
        categoria: 'Dragon Ball',
        pagina: 12,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874402/DB_FIG_012.png'
    },
    {
        id: 'DB_FIG_013',
        sku: 'DB_FIG_013',
        nombre: 'ARALE',
        tamaño: '15 cm',
        precioOferta: 35,
        descuento: 50,
        precioInflado: 52.50,
        descripcion: 'Figura de Arale de Dragon Ball - 15 cm.',
        palabrasClave: 'Dragon Ball, Arale, figura, crossover',
        categoria: 'Dragon Ball',
        pagina: 13,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874402/DB_FIG_013.png'
    },
    {
        id: 'DB_FIG_014',
        sku: 'DB_FIG_014',
        nombre: 'GOLDEN FREEZER',
        tamaño: '28 cm',
        precioOferta: 55,
        descuento: 20,
        precioInflado: 66.00,
        descripcion: 'Figura de Golden Freezer de Dragon Ball - 28 cm.',
        palabrasClave: 'Dragon Ball, Golden Freezer, figura, tamaño grande',
        categoria: 'Dragon Ball',
        pagina: 14,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874402/DB_FIG_014.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874401/DB_FIG_014_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874401/DB_FIG_014_2.png'
    },
    {
        id: 'DB_FIG_015',
        sku: 'DB_FIG_015',
        nombre: 'FREEZER',
        tamaño: '28 cm',
        precioOferta: 55,
        descuento: 30,
        precioInflado: 71.50,
        descripcion: 'Figura de Freezer de Dragon Ball - 28 cm.',
        palabrasClave: 'Dragon Ball, Freezer, figura, colección',
        categoria: 'Dragon Ball',
        pagina: 15,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874401/DB_FIG_015.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874403/DB_FIG_015_1.png'
    },
    {
        id: 'DB_SET_016',
        sku: 'DB_SET_016',
        nombre: 'GOKU COMIENDO',
        tamaño: '10 cm',
        precioOferta: 35,
        descuento: 40,
        precioInflado: 49.00,
        descripcion: 'Set de Goku comiendo de Dragon Ball - 10 cm.',
        palabrasClave: 'Dragon Ball, Goku, comiendo, set, figura',
        categoria: 'Dragon Ball Sets',
        pagina: 16,
        stock: 3,
        esSet: true,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874325/DB_SET_016.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874322/DB_SET_016_1.png'
    },
    {
        id: 'DB_SET_017',
        sku: 'DB_SET_017',
        nombre: 'VEGETA COMIENDO',
        tamaño: '10 cm',
        precioOferta: 35,
        descuento: 50,
        precioInflado: 52.50,
        descripcion: 'Set de Vegeta comiendo de Dragon Ball - 10 cm.',
        palabrasClave: 'Dragon Ball, Vegeta, comiendo, set, figura',
        categoria: 'Dragon Ball Sets',
        pagina: 17,
        stock: 3,
        esSet: true,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874322/DB_SET_017.png'
    },
    {
        id: 'DB_SET_018',
        sku: 'DB_SET_018',
        nombre: 'GOHAN COMIENDO',
        tamaño: '10 cm',
        precioOferta: 35,
        descuento: 20,
        precioInflado: 42.00,
        descripcion: 'Set de Gohan comiendo de Dragon Ball - 10 cm.',
        palabrasClave: 'Dragon Ball, Gohan, comiendo, set, figura',
        categoria: 'Dragon Ball Sets',
        pagina: 18,
        stock: 3,
        esSet: true,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874322/DB_SET_018.png'
    },
    {
        id: 'DB_SET_019',
        sku: 'DB_SET_019',
        nombre: 'N° 18 COMIENDO',
        tamaño: '10 cm',
        precioOferta: 35,
        descuento: 30,
        precioInflado: 45.50,
        descripcion: 'Set de Androide N° 18 comiendo de Dragon Ball - 10 cm.',
        palabrasClave: 'Dragon Ball, Androide 18, comiendo, set, figura',
        categoria: 'Dragon Ball Sets',
        pagina: 19,
        stock: 3,
        esSet: true,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874322/DB_SET_019.png'
    },
    {
        id: 'DB_SET_020',
        sku: 'DB_SET_020',
        nombre: 'KRILIN COMIENDO',
        tamaño: '10 cm',
        precioOferta: 35,
        descuento: 40,
        precioInflado: 49.00,
        descripcion: 'Set de Krilin comiendo de Dragon Ball - 10 cm.',
        palabrasClave: 'Dragon Ball, Krilin, comiendo, set, figura',
        categoria: 'Dragon Ball Sets',
        pagina: 20,
        stock: 3,
        esSet: true,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874321/DB_SET_020.png'
    },
    {
        id: 'DB_FIG_021',
        sku: 'DB_FIG_021',
        nombre: 'MAJIN VEGETA',
        tamaño: '21 cm',
        precioOferta: 39,
        descuento: 50,
        precioInflado: 58.50,
        descripcion: 'Figura de Majin Vegeta de Dragon Ball - 21 cm.',
        palabrasClave: 'Dragon Ball, Majin Vegeta, figura, acción',
        categoria: 'Dragon Ball',
        pagina: 21,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874320/DB_FIG_021.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874321/DB_FIG_021_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874320/DB_FIG_021_2.png'
    },
    {
        id: 'DB_FIG_022',
        sku: 'DB_FIG_022',
        nombre: 'GOKU SUPER SAYAYIN 1',
        tamaño: '16 cm',
        precioOferta: 35,
        descuento: 20,
        precioInflado: 42.00,
        descripcion: 'Figura de Goku Super Saiyan 1 de Dragon Ball - 16 cm.',
        palabrasClave: 'Dragon Ball, Goku, Super Saiyan 1, figura',
        categoria: 'Dragon Ball',
        pagina: 22,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874320/DB_FIG_022.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874322/DB_FIG_022_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874320/DB_FIG_022_2.png'
    },
    {
        id: 'DB_SET_023',
        sku: 'DB_SET_023',
        nombre: 'SET 13 FIGURAS DRAGON BALL',
        tamaño: '7 cm',
        precioOferta: 59,
        descuento: 30,
        precioInflado: 76.70,
        descripcion: 'Set de 13 figuras de Dragon Ball - 7 cm cada una.',
        palabrasClave: 'Dragon Ball, lote, 13 figuras, mini figuras, colección',
        categoria: 'Dragon Ball Sets',
        pagina: 23,
        stock: 3,
        esSet: true,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874319/DB_SET_023.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874318/DB_SET_023_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874318/DB_SET_023_2.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874318/DB_SET_023_3.png'
    },
    {
        id: 'DB_SET_024',
        sku: 'DB_SET_024',
        nombre: 'SET 8 TRANSFORMACIONES MAJIN BOO',
        tamaño: '8-12 cm',
        precioOferta: 59,
        descuento: 40,
        precioInflado: 82.60,
        descripcion: 'Set de 8 transformaciones de Majin Boo de Dragon Ball - 8 a 12 cm.',
        palabrasClave: 'Dragon Ball, Majin Boo, transformaciones, set, figuras',
        categoria: 'Dragon Ball Sets',
        pagina: 24,
        stock: 3,
        esSet: true,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874318/DB_SET_024.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874317/DB_SET_024_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874317/DB_SET_024_2.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874317/DB_SET_024_3.png'
    },
    {
        id: 'DB_SET_025',
        sku: 'DB_SET_025',
        nombre: 'SET 8 TRANSFORMACIONES FREEZER',
        tamaño: '8-12 cm',
        precioOferta: 59,
        descuento: 50,
        precioInflado: 88.50,
        descripcion: 'Set de 8 transformaciones de Freezer de Dragon Ball - 8 a 12 cm.',
        palabrasClave: 'Dragon Ball, Freezer, transformaciones, set, figuras',
        categoria: 'Dragon Ball Sets',
        pagina: 25,
        stock: 3,
        esSet: true,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874316/DB_SET_025.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874318/DB_SET_025_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874316/DB_SET_025_2.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874224/DB_SET_025_3.png'
    },
    {
        id: 'DB_SET_026',
        sku: 'DB_SET_026',
        nombre: 'SET 5 FIGURAS BOO',
        tamaño: '8 cm',
        precioOferta: 50,
        descuento: 20,
        precioInflado: 60.00,
        descripcion: 'Set de 5 figuras de Boo de Dragon Ball - 8 cm.',
        palabrasClave: 'Dragon Ball, Boo, set, figuras, colección',
        categoria: 'Dragon Ball Sets',
        pagina: 26,
        stock: 3,
        esSet: true,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874224/DB_SET_026.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874224/DB_SET_026_1.png'
    },
    {
        id: 'DB_SET_027',
        sku: 'DB_SET_027',
        nombre: 'SET 16 FIGURAS DRAGON BALL',
        tamaño: '7 cm',
        precioOferta: 59,
        descuento: 30,
        precioInflado: 76.70,
        descripcion: 'Set de 16 figuras de Dragon Ball - 7 cm.',
        palabrasClave: 'Dragon Ball, lote, 16 figuras, miniaturas',
        categoria: 'Dragon Ball Sets',
        pagina: 27,
        stock: 3,
        esSet: true,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874224/DB_SET_027.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874223/DB_SET_027_1.png'
    },
    {
        id: 'DB_SET_028',
        sku: 'DB_SET_028',
        nombre: 'SET 7 FIGURAS DRAGON BALL',
        tamaño: '9-10 cm',
        precioOferta: 80,
        descuento: 40,
        precioInflado: 112.00,
        descripcion: 'Set de 7 figuras de Dragon Ball - 9 a 10 cm.',
        palabrasClave: 'Dragon Ball, set, 7 figuras, tamaño mediano',
        categoria: 'Dragon Ball Sets',
        pagina: 28,
        stock: 3,
        esSet: true,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874223/DB_SET_028.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874223/DB_SET_028_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874224/DB_SET_028_2.png'
    },
    {
        id: 'DB_SET_029',
        sku: 'DB_SET_029',
        nombre: 'SET DE 8 FIGURAS',
        tamaño: '6-10 cm',
        precioOferta: 50,
        descuento: 50,
        precioInflado: 75.00,
        descripcion: 'Set de 8 figuras variadas de Dragon Ball - 6 a 10 cm.',
        palabrasClave: 'Dragon Ball, set, 8 figuras, lote',
        categoria: 'Dragon Ball Sets',
        pagina: 29,
        stock: 3,
        esSet: true,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874222/DB_SET_029.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874223/DB_SET_029_1.png'
    },
    {
        id: 'DB_FIG_030',
        sku: 'DB_FIG_030',
        nombre: 'GOKU Y PUAR',
        tamaño: '11 cm',
        precioOferta: 35,
        descuento: 20,
        precioInflado: 42.00,
        descripcion: 'Figura de Goku y Puar de Dragon Ball - 11 cm.',
        palabrasClave: 'Dragon Ball, Goku, Puar, dupla, figura',
        categoria: 'Dragon Ball',
        pagina: 30,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874221/DB_FIG_030.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874221/DB_FIG_030_1.png'
    },
    {
        id: 'DB_FIG_031',
        sku: 'DB_FIG_031',
        nombre: 'GOKU COLGANDO DE LA NUBE VOLADORA',
        tamaño: '9 cm',
        precioOferta: 35,
        descuento: 30,
        precioInflado: 45.50,
        descripcion: 'Figura de Goku colgando de la nube voladora - 9 cm.',
        palabrasClave: 'Dragon Ball, Goku, nube voladora, escena, figura',
        categoria: 'Dragon Ball',
        pagina: 31,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1/gkM2J7Nx/DB-FIG-031.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1/yY6N7Kh2/DB-FIG-031-1.png'
    },
    {
        id: 'DB_FIG_032',
        sku: 'DB_FIG_032',
        nombre: 'GOKU CON BÁCULO SAGRADO',
        tamaño: '14 cm',
        precioOferta: 35,
        descuento: 40,
        precioInflado: 49.00,
        descripcion: 'Figura de Goku con báculo sagrado de Dragon Ball - 14 cm.',
        palabrasClave: 'Dragon Ball, Goku, báculo sagrado, figura',
        categoria: 'Dragon Ball',
        pagina: 32,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1/dQj1M3C3/DB-FIG-032.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1/zDFBmvhL/DB-FIG-032-1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1/3NYx45s0/DB-FIG-032-2.png'
    },
    {
        id: 'DB_FIG_033',
        sku: 'DB_FIG_033',
        nombre: 'ESCENA GOKU VS PICCOLO',
        tamaño: '7.5 cm',
        precioOferta: 35,
        descuento: 50,
        precioInflado: 52.50,
        descripcion: 'Figura escena de Goku vs Piccolo de Dragon Ball - 7.5 cm.',
        palabrasClave: 'Dragon Ball, Goku, Piccolo, batalla, escena',
        categoria: 'Dragon Ball',
        pagina: 33,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874219/DB_FIG_033.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874200/DB_FIG_033_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874134/DB_FIG_033_2.png'
    },
    {
        id: 'DB_FIG_034',
        sku: 'DB_FIG_034',
        nombre: 'GOKU Y MAESTRO KARIN',
        tamaño: '12 cm',
        precioOferta: 35,
        descuento: 20,
        precioInflado: 42.00,
        descripcion: 'Figura de Goku y Maestro Karin de Dragon Ball - 12 cm.',
        palabrasClave: 'Dragon Ball, Goku, Karin, figura',
        categoria: 'Dragon Ball',
        pagina: 34,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1/0jPyMRTq/DB-FIG-034.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1/zBmBNRpC/DB-FIG-034-1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1/KzXzbgQY/DB-FIG-034-2.png'
    },
    {
        id: 'DB_FIG_035',
        sku: 'DB_FIG_035',
        nombre: 'BROLY',
        tamaño: '20 cm',
        precioOferta: 35,
        descuento: 30,
        precioInflado: 45.50,
        descripcion: 'Figura de Broly de Dragon Ball - 20 cm.',
        palabrasClave: 'Dragon Ball, Broly, figura, acción',
        categoria: 'Dragon Ball',
        pagina: 35,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874134/DB_FIG_035.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874134/DB_FIG_035_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874132/DB_FIG_035_2.png'
    },
    {
        id: 'DB_FIG_036',
        sku: 'DB_FIG_036',
        nombre: 'BILLS',
        tamaño: '30 cm',
        precioOferta: 59,
        descuento: 40,
        precioInflado: 82.60,
        descripcion: 'Figura de Bills de Dragon Ball - 30 cm.',
        palabrasClave: 'Dragon Ball, Bills, dios de la destrucción, figura grande',
        categoria: 'Dragon Ball',
        pagina: 36,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874132/DB_FIG_036.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874132/DB_FIG_036_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874132/DB_FIG_036_2.png'
    },
    {
        id: 'DB_FIG_037',
        sku: 'DB_FIG_037',
        nombre: 'SHENGLONG',
        tamaño: '18 cm',
        precioOferta: 55,
        descuento: 50,
        precioInflado: 82.50,
        descripcion: 'Figura de Shenglong de Dragon Ball - 18 cm.',
        palabrasClave: 'Dragon Ball, Shenglong, dragón, figura',
        categoria: 'Dragon Ball',
        pagina: 37,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874131/DB_FIG_037.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874132/DB_FIG_037_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874131/DB_FIG_037_2.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874131/DB_FIG_037_3.png'
    },
    {
        id: 'DB_FIG_038',
        sku: 'DB_FIG_038',
        nombre: 'ESCENA GOKU VS KRILIN',
        tamaño: '8 cm',
        precioOferta: 35,
        descuento: 20,
        precioInflado: 42.00,
        descripcion: 'Figura escena de Goku vs Krilin de Dragon Ball - 8 cm.',
        palabrasClave: 'Dragon Ball, Goku, Krilin, pelea, escena',
        categoria: 'Dragon Ball',
        pagina: 38,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874131/DB_FIG_038.png'
    },
    {
        id: 'DB_FIG_039',
        sku: 'DB_FIG_039',
        nombre: 'MAESTRO ROSHI Y BULMA',
        tamaño: '8 cm',
        precioOferta: 35,
        descuento: 30,
        precioInflado: 45.50,
        descripcion: 'Figura de Maestro Roshi y Bulma de Dragon Ball - 8 cm.',
        palabrasClave: 'Dragon Ball, Roshi, Bulma, figura',
        categoria: 'Dragon Ball',
        pagina: 39,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874131/DB_FIG_039.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874130/DB_FIG_039_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873916/DB_FIG_039_2.png'
    },
    {
        id: 'DB_FIG_040',
        sku: 'DB_FIG_040',
        nombre: 'BULMA',
        tamaño: '7 cm',
        precioOferta: 35,
        descuento: 40,
        precioInflado: 49.00,
        descripcion: 'Figura de Bulma de Dragon Ball - 7 cm.',
        palabrasClave: 'Dragon Ball, Bulma, mini figura',
        categoria: 'Dragon Ball',
        pagina: 40,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873893/DB_FIG_040.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873870/DB_FIG_040_1.png'
    },
    {
        id: 'DB_FIG_041',
        sku: 'DB_FIG_041',
        nombre: 'ESCENA - OZARU',
        tamaño: '7.5 cm',
        precioOferta: 35,
        descuento: 50,
        precioInflado: 52.50,
        descripcion: 'Figura escena de Ozaru de Dragon Ball - 7.5 cm.',
        palabrasClave: 'Dragon Ball, Ozaru, mono gigante, escena',
        categoria: 'Dragon Ball',
        pagina: 41,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873825/DB_FIG_041.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873824/DB_FIG_041_1.png'
    },
    {
        id: 'DB_FIG_042',
        sku: 'DB_FIG_042',
        nombre: 'GOKU',
        tamaño: '10 cm',
        precioOferta: 30,
        descuento: 20,
        precioInflado: 36.00,
        descripcion: 'Figura de Goku de Dragon Ball - 10 cm.',
        palabrasClave: 'Dragon Ball, Goku, figura básica',
        categoria: 'Dragon Ball',
        pagina: 42,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873824/DB_FIG_042.png,https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873824/DB_FIG_042_1.png'
    },
    {
        id: 'DB_FIG_043',
        sku: 'DB_FIG_043',
        nombre: 'PSYDUCK CELL',
        tamaño: '9 cm',
        precioOferta: 35,
        descuento: 20,
        precioInflado: 42.00,
        descripcion: 'Figura de Psyduck Cell (crossover) - 9 cm.',
        palabrasClave: 'Dragon Ball, Pokémon, crossover, Psyduck, Cell, figura',
        categoria: 'Dragon Ball',
        pagina: 43,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873824/DB_FIG_043.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873824/DB_FIG_043_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873824/DB_FIG_043_2.png'
    },
    {
        id: 'DB_FIG_044',
        sku: 'DB_FIG_044',
        nombre: 'GOKU EN MOTOCICLETA',
        tamaño: '13 cm',
        precioOferta: 50,
        descuento: 30,
        precioInflado: 65.00,
        descripcion: 'Figura de Goku en motocicleta de Dragon Ball - 13 cm.',
        palabrasClave: 'Dragon Ball, Goku, motocicleta, vehículo, figura',
        categoria: 'Dragon Ball',
        pagina: 44,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873812/DB_FIG_044.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873792/DB_FIG_044_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873713/DB_FIG_044_2.png'
    },
    {
        id: 'DB_FIG_045',
        sku: 'DB_FIG_045',
        nombre: 'MAJIN BOO EN MOTOCICLETA',
        tamaño: '11 cm',
        precioOferta: 50,
        descuento: 40,
        precioInflado: 70.00,
        descripcion: 'Figura de Majin Boo en motocicleta de Dragon Ball - 11 cm.',
        palabrasClave: 'Dragon Ball, Majin Boo, motocicleta, figura',
        categoria: 'Dragon Ball',
        pagina: 45,
        stock: 3,
        imagenes: 'hhttps://res.cloudinary.com/dwjiqcuin/image/upload/v1772874132/DB_FIG_045_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873713/DB_FIG_045.png'
    },
    {
        id: 'DB_FIG_046',
        sku: 'DB_FIG_046',
        nombre: 'FREEZER EN MOTOCICLETA',
        tamaño: '11 cm',
        precioOferta: 50,
        descuento: 50,
        precioInflado: 75.00,
        descripcion: 'Figura de Freezer en motocicleta de Dragon Ball - 11 cm.',
        palabrasClave: 'Dragon Ball, Freezer, motocicleta, figura',
        categoria: 'Dragon Ball',
        pagina: 46,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873713/DB_FIG_046.png'
    },
    {
        id: 'DB_FIG_047',
        sku: 'DB_FIG_047',
        nombre: 'CELL EN MOTOCICLETA',
        tamaño: '12 cm',
        precioOferta: 50,
        descuento: 20,
        precioInflado: 60.00,
        descripcion: 'Figura de Cell en motocicleta de Dragon Ball - 12 cm.',
        palabrasClave: 'Dragon Ball, Cell, motocicleta, figura',
        categoria: 'Dragon Ball',
        pagina: 47,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873713/DB_FIG_047.png'
    },
    {
        id: 'DB_FIG_048',
        sku: 'DB_FIG_048',
        nombre: 'GOHAN EN MOTOCICLETA',
        tamaño: '12 cm',
        precioOferta: 50,
        descuento: 30,
        precioInflado: 65.00,
        descripcion: 'Figura de Gohan en motocicleta de Dragon Ball - 12 cm.',
        palabrasClave: 'Dragon Ball, Gohan, motocicleta, figura',
        categoria: 'Dragon Ball',
        pagina: 48,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873713/DB_FIG_048.png'
    },
    {
        id: 'DB_FIG_049',
        sku: 'DB_FIG_049',
        nombre: 'MAESTRO ROSHI EN MOTOCICLETA',
        tamaño: '13 cm',
        precioOferta: 50,
        descuento: 40,
        precioInflado: 70.00,
        descripcion: 'Figura de Maestro Roshi en motocicleta de Dragon Ball - 13 cm.',
        palabrasClave: 'Dragon Ball, Roshi, motocicleta, figura',
        categoria: 'Dragon Ball',
        pagina: 49,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873713/DB_FIG_049.png'
    },
    {
        id: 'DB_FIG_050',
        sku: 'DB_FIG_050',
        nombre: 'GOKU NUBE VOLADORA',
        tamaño: '12 cm',
        precioOferta: 30,
        descuento: 50,
        precioInflado: 45.00,
        descripcion: 'Figura de Goku en nube voladora de Dragon Ball - 12 cm.',
        palabrasClave: 'Dragon Ball, Goku, nube voladora, figura',
        categoria: 'Dragon Ball',
        pagina: 50,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873712/DB_FIG_050.png'
    },
    {
        id: 'DB_VEH_051',
        sku: 'DB_VEH_051',
        nombre: 'MAQUINA DEL TIEMPO BULMA',
        tamaño: '8 cm',
        precioOferta: 39,
        descuento: 20,
        precioInflado: 46.80,
        descripcion: 'Vehículo máquina del tiempo de Bulma de Dragon Ball - 8 cm.',
        palabrasClave: 'Dragon Ball, máquina del tiempo, Bulma, vehículo',
        categoria: 'Dragon Ball Vehículos',
        pagina: 51,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873712/DB_VEH_051.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873712/DB_VEH_051_1.png'
    },
    {
        id: 'DB_VEH_052',
        sku: 'DB_VEH_052',
        nombre: 'MAQUINA DEL TIEMPO CELL',
        tamaño: '8 cm',
        precioOferta: 39,
        descuento: 30,
        precioInflado: 50.70,
        descripcion: 'Vehículo máquina del tiempo de Cell de Dragon Ball - 8 cm.',
        palabrasClave: 'Dragon Ball, máquina del tiempo, Cell, vehículo',
        categoria: 'Dragon Ball Vehículos',
        pagina: 52,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873712/DB_VEH_052.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873711/DB_VEH_052_1.png'
    },
    {
        id: 'DB_VEH_053',
        sku: 'DB_VEH_053',
        nombre: 'NAVE SAYAYIN DRAGON BALL',
        tamaño: '8 cm',
        precioOferta: 35,
        descuento: 40,
        precioInflado: 49.00,
        descripcion: 'Nave sayayin de Dragon Ball - 8 cm.',
        palabrasClave: 'Dragon Ball, nave, sayayin, vehículo',
        categoria: 'Dragon Ball Vehículos',
        pagina: 53,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873712/DB_VEH_053.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873711/DB_VEH_053_2.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873711/DB_VEH_053_1.png'
    },
    {
        id: 'DB_VEH_054',
        sku: 'DB_VEH_054',
        nombre: 'NAVE DRAGON BALL CAPSULA CORP',
        tamaño: '7 cm',
        precioOferta: 35,
        descuento: 50,
        precioInflado: 52.50,
        descripcion: 'Nave de Cápsula Corp de Dragon Ball - 7 cm.',
        palabrasClave: 'Dragon Ball, Cápsula Corp, nave, vehículo',
        categoria: 'Dragon Ball Vehículos',
        pagina: 54,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873711/DB_VEH_054.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873711/DB_VEH_054_1.png'
    },
    {
        id: 'DB_VEH_055',
        sku: 'DB_VEH_055',
        nombre: 'NAVE DRAGON BALL',
        tamaño: '7 cm',
        precioOferta: 35,
        descuento: 20,
        precioInflado: 42.00,
        descripcion: 'Nave de Dragon Ball - 7 cm.',
        palabrasClave: 'Dragon Ball, nave, vehículo',
        categoria: 'Dragon Ball Vehículos',
        pagina: 55,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873661/DB_VEH_055.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873661/DB_VEH_055_1.png'
    },

    // ============================================
    // NARUTO (OP_SET_056, OP_SET_057)
    // ============================================
    {
        id: 'OP_SET_056',
        sku: 'OP_SET_056',
        nombre: 'NARUTO SET DE 6 FIGURAS',
        tamaño: '8 cm',
        precioOferta: 40,
        descuento: 30,
        precioInflado: 52.00,
        descripcion: 'Set de 6 figuras de Naruto - 8 cm.',
        palabrasClave: 'Naruto, set, 6 figuras, anime, colección',
        categoria: 'Naruto',
        pagina: 56,
        stock: 3,
        esSet: true,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873661/OP_SET_056.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873661/OP_SET_056_1.png'
    },
    {
        id: 'OP_SET_057',
        sku: 'OP_SET_057',
        nombre: 'NARUTO SET DE 6 FIGURAS',
        tamaño: '8 cm',
        precioOferta: 40,
        descuento: 40,
        precioInflado: 56.00,
        descripcion: 'Set de 6 figuras de Naruto - 8 cm.',
        palabrasClave: 'Naruto, set, 6 figuras, anime',
        categoria: 'Naruto',
        pagina: 57,
        stock: 3,
        esSet: true,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873660/OP_SET_057.png'
    },

    // ============================================
    // ONE PIECE (OP_FIG_058 a OP_VEH_072)
    // ============================================
    {
        id: 'OP_FIG_058',
        sku: 'OP_FIG_058',
        nombre: 'LUFFY',
        tamaño: '17 cm',
        precioOferta: 35,
        descuento: 50,
        precioInflado: 52.50,
        descripcion: 'Figura de Luffy de One Piece - 17 cm.',
        palabrasClave: 'One Piece, Luffy, figura, acción',
        categoria: 'One Piece',
        pagina: 58,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873660/OP_FIG_058.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873660/OP_FIG_058_1.png'
    },
    {
        id: 'OP_FIG_059',
        sku: 'OP_FIG_059',
        nombre: 'LUFFY Flowing Cherry',
        tamaño: '24 cm',
        precioOferta: 45,
        descuento: 20,
        precioInflado: 54.00,
        descripcion: 'Figura de Luffy Flowing Cherry de One Piece - 24 cm.',
        palabrasClave: 'One Piece, Luffy, Flowing Cherry, figura grande',
        categoria: 'One Piece',
        pagina: 59,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873660/OP_FIG_059.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873659/OP_FIG_059_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873659/OP_FIG_059_2.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873660/OP_FIG_059_3.png'
    },
    {
        id: 'OP_FIG_060',
        sku: 'OP_FIG_060',
        nombre: 'LUFFY DIOS DEL SOL NIKA',
        tamaño: '10 cm',
        precioOferta: 24,
        descuento: 30,
        precioInflado: 31.20,
        descripcion: 'Figura de Luffy Dios del Sol Nika de One Piece - 10 cm.',
        palabrasClave: 'One Piece, Luffy, Nika, Gear 5, figura',
        categoria: 'One Piece',
        pagina: 60,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873660/OP_FIG_060.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873659/OP_FIG_060_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873659/OP_FIG_060_2.png'
    },
    {
        id: 'OP_FIG_061',
        sku: 'OP_FIG_061',
        nombre: 'LUFFY Y SHANKS',
        tamaño: '16 cm',
        precioOferta: 40,
        descuento: 40,
        precioInflado: 56.00,
        descripcion: 'Figura de Luffy y Shanks de One Piece - 16 cm.',
        palabrasClave: 'One Piece, Luffy, Shanks, dupla, figura',
        categoria: 'One Piece',
        pagina: 61,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873658/OP_FIG_061.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873657/OP_FIG_061_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873658/OP_FIG_061_2.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873658/OP_FIG_061_3.png'
    },
    {
        id: 'OP_FIG_062',
        sku: 'OP_FIG_062',
        nombre: 'LUFFY CON ROSTRO INTERCAMBIABLE',
        tamaño: '28 cm',
        precioOferta: 59,
        descuento: 50,
        precioInflado: 88.50,
        descripcion: 'Figura de Luffy con rostro intercambiable de One Piece - 28 cm.',
        palabrasClave: 'One Piece, Luffy, rostro intercambiable, figura grande',
        categoria: 'One Piece',
        pagina: 62,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873656/OP_FIG_062.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873621/OP_FIG_062_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873622/OP_FIG_062_2.png'
    },
    {
        id: 'OP_FIG_063',
        sku: 'OP_FIG_063',
        nombre: 'MONKEY D. LUFFY GEAR 5',
        tamaño: '19 cm',
        precioOferta: 39,
        descuento: 20,
        precioInflado: 46.80,
        descripcion: 'Figura de Monkey D. Luffy Gear 5 de One Piece - 19 cm.',
        palabrasClave: 'One Piece, Luffy, Gear 5, figura',
        categoria: 'One Piece',
        pagina: 63,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873621/OP_FIG_063.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873621/OP_FIG_063_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873620/OP_FIG_063_2.png'
    },
    {
        id: 'OP_FIG_064',
        sku: 'OP_FIG_064',
        nombre: 'LUFFY',
        tamaño: '12 cm',
        precioOferta: 30,
        descuento: 30,
        precioInflado: 39.00,
        descripcion: 'Figura de Luffy de One Piece - 12 cm.',
        palabrasClave: 'One Piece, Luffy, figura',
        categoria: 'One Piece',
        pagina: 64,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873620/OP_FIG_064.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873620/OP_FIG_064_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873620/OP_FIG_064_2.png'
    },
    {
        id: 'OP_FIG_065',
        sku: 'OP_FIG_065',
        nombre: 'MONKEY D. LUFFY GEAR 5 POSE DE BATALLA',
        tamaño: '18 cm',
        precioOferta: 35,
        descuento: 40,
        precioInflado: 49.00,
        descripcion: 'Figura de Luffy Gear 5 pose de batalla de One Piece - 18 cm.',
        palabrasClave: 'One Piece, Luffy, Gear 5, batalla, figura',
        categoria: 'One Piece',
        pagina: 65,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873620/OP_FIG_065.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873620/OP_FIG_065_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873620/OP_FIG_065_1.png'
    },
    {
        id: 'OP_FIG_066',
        sku: 'OP_FIG_066',
        nombre: 'NAMI',
        tamaño: '19 cm',
        precioOferta: 35,
        descuento: 50,
        precioInflado: 52.50,
        descripcion: 'Figura de Nami de One Piece - 19 cm.',
        palabrasClave: 'One Piece, Nami, figura femenina',
        categoria: 'One Piece',
        pagina: 66,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873619/OP_FIG_066.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873620/OP_FIG_066_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873620/OP_FIG_066_1.png'
    },
    {
        id: 'OP_SET_067',
        sku: 'OP_SET_067',
        nombre: 'SET DE 6 FIGURAS ONE PIECE',
        tamaño: '8 cm',
        precioOferta: 49,
        descuento: 20,
        precioInflado: 58.80,
        descripcion: 'Set de 6 figuras de One Piece - 8 cm.',
        palabrasClave: 'One Piece, set, 6 figuras, mini figuras',
        categoria: 'One Piece',
        pagina: 67,
        stock: 3,
        esSet: true,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873583/OP_SET_067.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873583/OP_SET_067_1.png'
    },
    {
        id: 'OP_FIG_068',
        sku: 'OP_FIG_068',
        nombre: 'ZORO',
        tamaño: '12 cm',
        precioOferta: 35,
        descuento: 30,
        precioInflado: 45.50,
        descripcion: 'Figura de Zoro de One Piece - 12 cm.',
        palabrasClave: 'One Piece, Zoro, figura, espadas',
        categoria: 'One Piece',
        pagina: 68,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873583/OP_FIG_068.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873583/OP_FIG_068_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873582/OP_FIG_068_2.png,  https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873582/OP_FIG_068_3.png'
    },
    {
        id: 'OP_FIG_069',
        sku: 'OP_FIG_069',
        nombre: 'SANJI',
        tamaño: '12x15 cm',
        precioOferta: 35,
        descuento: 40,
        precioInflado: 49.00,
        descripcion: 'Figura de Sanji de One Piece - 12x15 cm.',
        palabrasClave: 'One Piece, Sanji, figura, cocinero',
        categoria: 'One Piece',
        pagina: 69,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873582/OP_FIG_069.png. https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873582/OP_FIG_069_1.png'
    },
    {
        id: 'OP_FIG_070',
        sku: 'OP_FIG_070',
        nombre: 'ACE',
        tamaño: '12 cm',
        precioOferta: 30,
        descuento: 50,
        precioInflado: 45.00,
        descripcion: 'Figura de Ace de One Piece - 12 cm.',
        palabrasClave: 'One Piece, Ace, figura, fuego',
        categoria: 'One Piece',
        pagina: 70,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873582/OP_FIG_070.png'
    },
    {
        id: 'OP_VEH_071',
        sku: 'OP_VEH_071',
        nombre: 'BARCO ONE PIECE',
        tamaño: '7x8 cm',
        precioOferta: 24,
        descuento: 20,
        precioInflado: 28.80,
        descripcion: 'Barco de One Piece - 7x8 cm.',
        palabrasClave: 'One Piece, barco, Thousand Sunny, vehículo',
        categoria: 'One Piece Vehículos',
        pagina: 71,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873581/OP_VEH_071.png. https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873582/OP_VEH_071_1.png'
    },
    {
        id: 'OP_VEH_072',
        sku: 'OP_VEH_072',
        nombre: 'BARCO ONE PIECE',
        tamaño: '7x8 cm',
        precioOferta: 24,
        descuento: 30,
        precioInflado: 31.20,
        descripcion: 'Barco de One Piece - 7x8 cm.',
        palabrasClave: 'One Piece, barco, Going Merry, vehículo',
        categoria: 'One Piece Vehículos',
        pagina: 72,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873582/OP_VEH_072.png'
    },

    // ============================================
    // MARVEL (MV_FIG_073 a MV_FIG_079)
    // ============================================
    {
        id: 'MV_FIG_073',
        sku: 'MV_FIG_073',
        nombre: 'IRON MAN',
        tamaño: '12 cm',
        precioOferta: 35,
        descuento: 40,
        precioInflado: 49.00,
        descripcion: 'Figura de Iron Man de Marvel - 12 cm.',
        palabrasClave: 'Marvel, Iron Man, figura, superhéroe',
        categoria: 'Marvel',
        pagina: 73,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873582/OP_VEH_072.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873535/MV_FIG_073_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873535/MV_FIG_073_1.png'
    },
    {
        id: 'MV_FIG_074',
        sku: 'MV_FIG_074',
        nombre: 'CAPITAN AMÉRICA',
        tamaño: '13 cm',
        precioOferta: 35,
        descuento: 50,
        precioInflado: 52.50,
        descripcion: 'Figura de Capitán América de Marvel - 13 cm.',
        palabrasClave: 'Marvel, Capitán América, figura, escudo',
        categoria: 'Marvel',
        pagina: 74,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873535/MV_FIG_073_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873535/MV_FIG_074_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873534/MV_FIG_074_2.png'
    },
    {
        id: 'MV_FIG_075',
        sku: 'MV_FIG_075',
        nombre: 'SPIDER MAN',
        tamaño: '12 cm',
        precioOferta: 35,
        descuento: 20,
        precioInflado: 42.00,
        descripcion: 'Figura de Spider Man de Marvel - 12 cm.',
        palabrasClave: 'Marvel, Spider Man, figura, trepamuros',
        categoria: 'Marvel',
        pagina: 75,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873536/MV_FIG_075.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873534/MV_FIG_075_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873534/MV_FIG_075_2.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873533/MV_FIG_075_3.png'
    },
    {
        id: 'MV_SET_076',
        sku: 'MV_SET_076',
        nombre: 'SET 4 SPIDER MAN',
        tamaño: '6-8 cm',
        precioOferta: 35,
        descuento: 20,
        precioInflado: 42.00,
        descripcion: 'Set de 4 figuras de Spider Man - 6 a 8 cm.',
        palabrasClave: 'Marvel, Spider Man, set, 4 figuras',
        categoria: 'Marvel',
        pagina: 76,
        stock: 3,
        esSet: true,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873536/MV_FIG_075.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873532/MV_SET_076_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873532/MV_SET_076_2.png'
    },
    {
        id: 'MV_SET_077',
        sku: 'MV_SET_077',
        nombre: 'SET 3 FIGURAS DEADPOOL',
        tamaño: '-',
        precioOferta: 30,
        descuento: 30,
        precioInflado: 39.00,
        descripcion: 'Set de 3 figuras de Deadpool - tamaño variable.',
        palabrasClave: 'Marvel, Deadpool, set, 3 figuras',
        categoria: 'Marvel',
        pagina: 77,
        stock: 3,
        esSet: true,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873532/MV_SET_076_2.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873533/MV_SET_077_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873532/MV_SET_077_2.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873532/MV_SET_077_2.png'
    },
    {
        id: 'MV_SET_078',
        sku: 'MV_SET_078',
        nombre: 'SET 4 FIGURAS DE GROOT',
        tamaño: '5 cm',
        precioOferta: 25,
        descuento: 40,
        precioInflado: 35.00,
        descripcion: 'Set de 4 figuras de Groot - 5 cm.',
        palabrasClave: 'Marvel, Groot, set, 4 figuras, baby Groot',
        categoria: 'Marvel',
        pagina: 78,
        stock: 3,
        esSet: true,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873489/MV_SET_078.png. https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873825/MV_SET_078_1.png'
    },
    {
        id: 'MV_FIG_079',
        sku: 'MV_FIG_079',
        nombre: 'SUPER MAN',
        tamaño: '15 cm',
        precioOferta: 35,
        descuento: 50,
        precioInflado: 52.50,
        descripcion: 'Figura de Superman de DC - 15 cm.',
        palabrasClave: 'DC, Superman, figura, superhéroe',
        categoria: 'DC',
        pagina: 79,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873488/MV_FIG_079.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873488/MV_FIG_079_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873488/MV_FIG_079_2.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873488/MV_FIG_079_3.png '
    },

    // ============================================
    // POKEMON (PK_SET_080 a PK_FIG_093)
    // ============================================
    {
        id: 'PK_SET_080',
        sku: 'PK_SET_080',
        nombre: 'SET DE 6 POKEMONS',
        tamaño: '6-7 cm',
        precioOferta: 59,
        descuento: 20,
        precioInflado: 70.80,
        descripcion: 'Set de 6 Pokémons - 6 a 7 cm.',
        palabrasClave: 'Pokémon, set, 6 figuras, miniaturas',
        categoria: 'Pokemon',
        pagina: 80,
        stock: 3,
        esSet: true,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873488/PK_SET_080.png,  https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873487/PK_SET_080_1.png , https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873487/PK_SET_080_2.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873487/PK_SET_080_3.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873487/PK_SET_080_4.png'
    },
    {
        id: 'PK_SET_081',
        sku: 'PK_SET_081',
        nombre: 'SET DE 8 POKEMONS',
        tamaño: '4-5 cm',
        precioOferta: 35,
        descuento: 30,
        precioInflado: 45.50,
        descripcion: 'Set de 8 Pokémons - 4 a 5 cm.',
        palabrasClave: 'Pokémon, set, 8 figuras, mini',
        categoria: 'Pokemon',
        pagina: 81,
        stock: 3,
        esSet: true,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873486/PK_SET_081.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873486/PK_SET_081_1.png,  https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873486/PK_SET_081_2.png'
    },
    {
        id: 'PK_SET_082',
        sku: 'PK_SET_082',
        nombre: 'SET DE 5 SNORLAX',
        tamaño: '3.5 cm',
        precioOferta: 30,
        descuento: 40,
        precioInflado: 42.00,
        descripcion: 'Set de 5 Snorlax - 3.5 cm.',
        palabrasClave: 'Pokémon, Snorlax, set, 5 figuras',
        categoria: 'Pokemon',
        pagina: 82,
        stock: 3,
        esSet: true,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873486/PK_SET_082.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873486/PK_SET_082_1.png'
    },
    {
        id: 'PK_SET_083',
        sku: 'PK_SET_083',
        nombre: 'POKEBOLA + 24 POKEMON',
        tamaño: '7x7 cm / 3 cm',
        precioOferta: 30,
        descuento: 50,
        precioInflado: 45.00,
        descripcion: 'Pokebola con 24 Pokémons - 7x7 cm y 3 cm.',
        palabrasClave: 'Pokémon, pokebola, set, 24 figuras',
        categoria: 'Pokemon',
        pagina: 83,
        stock: 3,
        esSet: true,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873487/PK_SET_083.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873479/PK_SET_083_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873443/PK_SET_083_2.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873444/PK_SET_083_3.png'
    },
    {
        id: 'PK_LMP_084',
        sku: 'PK_LMP_084',
        nombre: 'LÁMPARA DE PIKACHU',
        tamaño: '13 cm',
        precioOferta: 28,
        descuento: 20,
        precioInflado: 33.60,
        descripcion: 'Lámpara de Pikachu - 13 cm.',
        palabrasClave: 'Pokémon, Pikachu, lámpara, luz nocturna',
        categoria: 'Pokemon Lámparas',
        pagina: 84,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873443/PK_LMP_084.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873443/PK_LMP_084_1.png'
    },
    {
        id: 'PK_LMP_085',
        sku: 'PK_LMP_085',
        nombre: 'LÁMPARA DE PSYDUCK',
        tamaño: '10x8 cm',
        precioOferta: 28,
        descuento: 30,
        precioInflado: 36.40,
        descripcion: 'Lámpara de Psyduck - 10x8 cm.',
        palabrasClave: 'Pokémon, Psyduck, lámpara, decoración',
        categoria: 'Pokemon Lámparas',
        pagina: 85,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873443/PK_LMP_085.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873442/PK_LMP_085_1.png'
    },
    {
        id: 'PK_LMP_086',
        sku: 'PK_LMP_086',
        nombre: 'LÁMPARA DE GENGAR',
        tamaño: '10x10 cm',
        precioOferta: 28,
        descuento: 40,
        precioInflado: 39.20,
        descripcion: 'Lámpara de Gengar - 10x10 cm.',
        palabrasClave: 'Pokémon, Gengar, lámpara, ambientador',
        categoria: 'Pokemon Lámparas',
        pagina: 86,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873442/PK_LMP_086.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873442/PK_LMP_086_1.png'
    },
    {
        id: 'PK_FIG_087',
        sku: 'PK_FIG_087',
        nombre: 'CUBONE',
        tamaño: '8 cm',
        precioOferta: 24,
        descuento: 50,
        precioInflado: 36.00,
        descripcion: 'Figura de Cubone de Pokémon - 8 cm.',
        palabrasClave: 'Pokémon, Cubone, figura',
        categoria: 'Pokemon',
        pagina: 87,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873441/PK_FIG_087.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873441/PK_FIG_087_4.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873441/PK_FIG_087_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873441/PK_FIG_087_3.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873441/PK_FIG_087_2.png'
    },
    {
        id: 'PK_FIG_088',
        sku: 'PK_FIG_088',
        nombre: 'BULBASAUR CON ALMOHADA',
        tamaño: '8 cm',
        precioOferta: 25,
        descuento: 20,
        precioInflado: 30.00,
        descripcion: 'Figura de Bulbasaur con almohada - 8 cm.',
        palabrasClave: 'Pokémon, Bulbasaur, almohada, figura',
        categoria: 'Pokemon',
        pagina: 88,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873441/PK_FIG_088.png'
    },
    {
        id: 'PK_FIG_089',
        sku: 'PK_FIG_089',
        nombre: 'KOMALA CON ALMOHADA',
        tamaño: '8 cm',
        precioOferta: 25,
        descuento: 30,
        precioInflado: 32.50,
        descripcion: 'Figura de Komala con almohada - 8 cm.',
        palabrasClave: 'Pokémon, Komala, almohada, figura',
        categoria: 'Pokemon',
        pagina: 89,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873402/PK_FIG_089.png'
    },
    {
        id: 'PK_FIG_090',
        sku: 'PK_FIG_090',
        nombre: 'SNORLAX CON ALMOHADA',
        tamaño: '8 cm',
        precioOferta: 25,
        descuento: 40,
        precioInflado: 35.00,
        descripcion: 'Figura de Snorlax con almohada - 8 cm.',
        palabrasClave: 'Pokémon, Snorlax, almohada, figura',
        categoria: 'Pokemon',
        pagina: 90,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873402/PK_FIG_090.png'
    },
    {
        id: 'PK_FIG_091',
        sku: 'PK_FIG_091',
        nombre: 'PIKACHU CON ALMOHADA',
        tamaño: '8 cm',
        precioOferta: 25,
        descuento: 50,
        precioInflado: 37.50,
        descripcion: 'Figura de Pikachu con almohada - 8 cm.',
        palabrasClave: 'Pokémon, Pikachu, almohada, figura',
        categoria: 'Pokemon',
        pagina: 91,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873402/PK_FIG_091.png'
    },
    {
        id: 'PK_FIG_092',
        sku: 'PK_FIG_092',
        nombre: 'EEVEE CON ALMOHADA',
        tamaño: '8 cm',
        precioOferta: 25,
        descuento: 20,
        precioInflado: 30.00,
        descripcion: 'Figura de Eevee con almohada - 8 cm.',
        palabrasClave: 'Pokémon, Eevee, almohada, figura',
        categoria: 'Pokemon',
        pagina: 92,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873401/PK_FIG_092.png'
    },
    {
        id: 'PK_FIG_093',
        sku: 'PK_FIG_093',
        nombre: 'JIRACHI CON ALMOHADA',
        tamaño: '8 cm',
        precioOferta: 25,
        descuento: 30,
        precioInflado: 32.50,
        descripcion: 'Figura de Jirachi con almohada - 8 cm.',
        palabrasClave: 'Pokémon, Jirachi, almohada, figura',
        categoria: 'Pokemon',
        pagina: 93,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873401/PK_FIG_093.png'
    },

    // ============================================
    // DEMON SLAYER (DS_SET_094 a DS_FIG_106)
    // ============================================
    {
        id: 'DS_SET_094',
        sku: 'DS_SET_094',
        nombre: 'SET DE 15 FIGURAS DEMON SLAYER',
        tamaño: '5 cm',
        precioOferta: 99,
        descuento: 40,
        precioInflado: 138.60,
        descripcion: 'Set de 15 figuras de Demon Slayer - 5 cm.',
        palabrasClave: 'Demon Slayer, Kimetsu no Yaiba, set, 15 figuras',
        categoria: 'Demon Slayer',
        pagina: 94,
        stock: 3,
        esSet: true,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873401/DS_SET_094.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873401/DS_SET_094_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873400/DS_SET_094_2.png'
    },
    {
        id: 'DS_SET_095',
        sku: 'DS_SET_095',
        nombre: 'SET 6 FIGURAS DEMON SLAYER',
        tamaño: '8 cm',
        precioOferta: 40,
        descuento: 50,
        precioInflado: 60.00,
        descripcion: 'Set de 6 figuras de Demon Slayer - 8 cm.',
        palabrasClave: 'Demon Slayer, set, 6 figuras, mini',
        categoria: 'Demon Slayer',
        pagina: 95,
        stock: 3,
        esSet: true,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873402/DS_SET_095.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873400/DS_SET_095_2.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873401/DS_SET_095_1.png'
    },
    {
        id: 'DS_FIG_096',
        sku: 'DS_FIG_096',
        nombre: 'TANJIRO KAMARO DEMON SLAYER',
        tamaño: '16 cm',
        precioOferta: 35,
        descuento: 20,
        precioInflado: 42.00,
        descripcion: 'Figura de Tanjiro Kamado de Demon Slayer - 16 cm.',
        palabrasClave: 'Demon Slayer, Tanjiro, figura, acción',
        categoria: 'Demon Slayer',
        pagina: 96,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873399/DS_SET_096.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873400/DS_SET_096_1.png'
    },
    {
        id: 'DS_FIG_097',
        sku: 'DS_FIG_097',
        nombre: 'NEZUKO KAMADO DEMON SLAYER',
        tamaño: '16 cm',
        precioOferta: 35,
        descuento: 30,
        precioInflado: 45.50,
        descripcion: 'Figura de Nezuko Kamado de Demon Slayer - 16 cm.',
        palabrasClave: 'Demon Slayer, Nezuko, figura, bambú',
        categoria: 'Demon Slayer',
        pagina: 97,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873399/DS_FIG_097.png'
    },
    {
        id: 'DS_FIG_098',
        sku: 'DS_FIG_098',
        nombre: 'VIBRATION STARS NEZUKO KAMADO DEMON SLAYER',
        tamaño: '19 cm',
        precioOferta: 39,
        descuento: 40,
        precioInflado: 54.60,
        descripcion: 'Figura Vibration Stars de Nezuko de Demon Slayer - 19 cm.',
        palabrasClave: 'Demon Slayer, Nezuko, Vibration Stars, figura',
        categoria: 'Demon Slayer',
        pagina: 98,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873399/DS_FIG_098.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873386/DS_FIG_098_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873352/DS_FIG_098_2.png'
    },
    {
        id: 'DS_FIG_099',
        sku: 'DS_FIG_099',
        nombre: 'SHINOBU KOCHO DEMON SLAYER',
        tamaño: '16 cm',
        precioOferta: 35,
        descuento: 50,
        precioInflado: 52.50,
        descripcion: 'Figura de Shinobu Kocho de Demon Slayer - 16 cm.',
        palabrasClave: 'Demon Slayer, Shinobu, figura, insecto',
        categoria: 'Demon Slayer',
        pagina: 99,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873352/DS_FIG_099_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873353/DS_FIG_099.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873352/DS_FIG_099_2.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873352/DS_FIG_099_3.png'
    },
    {
        id: 'DS_FIG_100',
        sku: 'DS_FIG_100',
        nombre: 'OBANAI IGURO DEMON SLAYER',
        tamaño: '16 cm',
        precioOferta: 35,
        descuento: 20,
        precioInflado: 42.00,
        descripcion: 'Figura de Obanai Iguro de Demon Slayer - 16 cm.',
        palabrasClave: 'Demon Slayer, Obanai, figura, serpiente',
        categoria: 'Demon Slayer',
        pagina: 100,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873351/DS_FIG_100.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873351/DS_FIG_100_2.png,  https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873351/DS_FIG_100_1.png'
    },
    {
        id: 'DS_FIG_101',
        sku: 'DS_FIG_101',
        nombre: 'INOSUKE HASHIBIRA DEMON SLAYER',
        tamaño: '16 cm',
        precioOferta: 35,
        descuento: 30,
        precioInflado: 45.50,
        descripcion: 'Figura de Inosuke Hashibira de Demon Slayer - 16 cm.',
        palabrasClave: 'Demon Slayer, Inosuke, figura, máscara',
        categoria: 'Demon Slayer',
        pagina: 101,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873351/DS_FIG_101.png'
    },
    {
        id: 'DS_FIG_102',
        sku: 'DS_FIG_102',
        nombre: 'AKAZA DEMON SLAYER',
        tamaño: '16 cm',
        precioOferta: 35,
        descuento: 40,
        precioInflado: 49.00,
        descripcion: 'Figura de Akaza de Demon Slayer - 16 cm.',
        palabrasClave: 'Demon Slayer, Akaza, figura, demonio',
        categoria: 'Demon Slayer',
        pagina: 102,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873351/DS_FIG_102.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873351/DS_FIG_102_3.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873350/DS_FIG_102_2.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873350/DS_FIG_102_1.png'
    },
    {
        id: 'DS_FIG_103',
        sku: 'DS_FIG_103',
        nombre: 'MUZAN KIBUTSUJI DEMON SLAYER',
        tamaño: '16 cm',
        precioOferta: 35,
        descuento: 50,
        precioInflado: 52.50,
        descripcion: 'Figura de Muzan Kibutsuji de Demon Slayer - 16 cm.',
        palabrasClave: 'Demon Slayer, Muzan, figura, rey demonio',
        categoria: 'Demon Slayer',
        pagina: 103,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873314/DS_FIG_103_2.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873314/DS_FIG_103_2.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873350/DS_FIG_103_1.png'
    },
    {
        id: 'DS_FIG_104',
        sku: 'DS_FIG_104',
        nombre: 'ZENITSU AGATSUMA DEMON SLAYER',
        tamaño: '16 cm',
        precioOferta: 35,
        descuento: 20,
        precioInflado: 42.00,
        descripcion: 'Figura de Zenitsu Agatsuma de Demon Slayer - 16 cm.',
        palabrasClave: 'Demon Slayer, Zenitsu, figura, rayo',
        categoria: 'Demon Slayer',
        pagina: 104,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873313/DS_FIG_104.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873313/DS_FIG_104_1.png'
    },
    {
        id: 'DS_FIG_105',
        sku: 'DS_FIG_105',
        nombre: 'MITSURI KANROJI DEMON SLAYER',
        tamaño: '16 cm',
        precioOferta: 35,
        descuento: 30,
        precioInflado: 45.50,
        descripcion: 'Figura de Mitsuri Kanroji de Demon Slayer - 16 cm.',
        palabrasClave: 'Demon Slayer, Mitsuri, figura, amor',
        categoria: 'Demon Slayer',
        pagina: 105,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873313/DS_FIG_105.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873313/DS_FIG_105_2.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873312/DS_FIG_105_3.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873313/DS_FIG_105_1.png'
    },
    {
        id: 'DS_FIG_106',
        sku: 'DS_FIG_106',
        nombre: 'GIYU TOMIOKA DEMON SLAYER',
        tamaño: '16 cm',
        precioOferta: 35,
        descuento: 40,
        precioInflado: 49.00,
        descripcion: 'Figura de Giyu Tomioka de Demon Slayer - 16 cm.',
        palabrasClave: 'Demon Slayer, Giyu, figura, agua',
        categoria: 'Demon Slayer',
        pagina: 106,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873312/DS_FIG_106_2.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873312/DS_FIG_106.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873312/DS_FIG_106_1.png'
    },

    // ============================================
    // VARIOS (BTS, Digimon, Bob Esponja, etc.)
    // ============================================
    {
        id: 'BT_SET_107',
        sku: 'BT_SET_107',
        nombre: 'SET DE 7 FIGURAS DE BTS',
        tamaño: '8 cm',
        precioOferta: 65,
        descuento: 50,
        precioInflado: 97.50,
        descripcion: 'Set de 7 figuras de BTS - 8 cm.',
        palabrasClave: 'BTS, k-pop, set, 7 figuras, idol',
        categoria: 'BTS',
        pagina: 107,
        stock: 3,
        esSet: true,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873312/BT_SET_107.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873312/BT_SET_107_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873311/BT_SET_107_2.png'
    },
    {
        id: 'DG_SET_108',
        sku: 'DG_SET_108',
        nombre: 'SET 9 FIGURAS DIGIMON',
        tamaño: '4-5 cm',
        precioOferta: 40,
        descuento: 20,
        precioInflado: 48.00,
        descripcion: 'Set de 9 figuras de Digimon - 4 a 5 cm.',
        palabrasClave: 'Digimon, set, 9 figuras, mini',
        categoria: 'Digimon',
        pagina: 108,
        stock: 3,
        esSet: true,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772874449/DG_SET_108.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872604/DG_SET_108_2.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772873204/DG_SET_108_1.png'
    },
    {
        id: 'SB_SET_109',
        sku: 'SB_SET_109',
        nombre: 'SET 6 FIGURAS DE BOB ESPONJA',
        tamaño: '-',
        precioOferta: 25,
        descuento: 20,
        precioInflado: 30.00,
        descripcion: 'Set de 6 figuras de Bob Esponja - tamaño variable.',
        palabrasClave: 'Bob Esponja, SpongeBob, set, 6 figuras',
        categoria: 'Bob Esponja',
        pagina: 109,
        stock: 3,
        esSet: true,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872583/SB_SET_109.png'
    },
    {
        id: 'SM_SET_110',
        sku: 'SM_SET_110',
        nombre: 'SUPER MARIO BROS SET DE 6 FIGURAS',
        tamaño: '4-6 cm',
        precioOferta: 35,
        descuento: 30,
        precioInflado: 45.50,
        descripcion: 'Set de 6 figuras de Super Mario Bros - 4 a 6 cm.',
        palabrasClave: 'Super Mario, Mario Bros, set, 6 figuras, Nintendo',
        categoria: 'Super Mario',
        pagina: 110,
        stock: 3,
        esSet: true,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872560/SM_SET_110.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872504/SM_SET_110_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872504/SM_SET_110_2.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872503/SM_SET_110_3.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872503/SM_SET_110_4.png'
    },
    {
        id: 'MM_SET_111',
        sku: 'MM_SET_111',
        nombre: 'SET 6 FIGURAS MICKEY MOUSE',
        tamaño: '6 cm',
        precioOferta: 35,
        descuento: 40,
        precioInflado: 49.00,
        descripcion: 'Set de 6 figuras de Mickey Mouse - 6 cm.',
        palabrasClave: 'Mickey Mouse, Disney, set, 6 figuras',
        categoria: 'Mickey Mouse',
        pagina: 111,
        stock: 3,
        esSet: true,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872504/MM_SET_111.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872503/MM_SET_111_1.png'
    },
    {
        id: 'YG_FIG_112',
        sku: 'YG_FIG_112',
        nombre: 'YU GIOH',
        tamaño: '13 cm',
        precioOferta: 35,
        descuento: 50,
        precioInflado: 52.50,
        descripcion: 'Figura de Yu-Gi-Oh! - 13 cm.',
        palabrasClave: 'Yu-Gi-Oh!, figura, anime',
        categoria: 'Yu-Gi-Oh!',
        pagina: 112,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872503/YG_FIG_112.png'
    },
    {
        id: 'TS_SET_113',
        sku: 'TS_SET_113',
        nombre: 'TOY STORY SET DE 8 FIGURAS',
        tamaño: '4-5 cm',
        precioOferta: 40,
        descuento: 20,
        precioInflado: 48.00,
        descripcion: 'Set de 8 figuras de Toy Story - 4 a 5 cm.',
        palabrasClave: 'Toy Story, Disney, set, 8 figuras, mini',
        categoria: 'Toy Story',
        pagina: 113,
        stock: 3,
        esSet: true,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872503/TS_SET_113.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872503/TS_SET_113_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872502/TS_SET_113_2.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872502/TS_SET_113_3.png'
    },
    {
        id: 'HR_SET_114',
        sku: 'HR_SET_114',
        nombre: 'SET DE 10 FIGURAS DE PELÍCULAS DE TERROR',
        tamaño: '5 cm',
        precioOferta: 59,
        descuento: 30,
        precioInflado: 76.70,
        descripcion: 'Set de 10 figuras de películas de terror - 5 cm.',
        palabrasClave: 'Terror, horror, set, 10 figuras, Freddy, Jason',
        categoria: 'Terror',
        pagina: 114,
        stock: 3,
        esSet: true,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872502/HR_SET_114.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872502/HR_SET_114_1.png'
    },
    {
        id: 'HK_SET_115',
        sku: 'HK_SET_115',
        nombre: 'SET 8 FIGURAS HELLO KITTY',
        tamaño: '8 cm',
        precioOferta: 25,
        descuento: 40,
        precioInflado: 35.00,
        descripcion: 'Set de 8 figuras de Hello Kitty - 8 cm.',
        palabrasClave: 'Hello Kitty, Sanrio, set, 8 figuras',
        categoria: 'Hello Kitty',
        pagina: 115,
        stock: 3,
        esSet: true,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872502/HK_SET_115.png'
    },
    {
        id: 'LS_SET_116',
        sku: 'LS_SET_116',
        nombre: 'SET DE 6 FIGURAS LILO Y STITCH',
        tamaño: '2 cm',
        precioOferta: 25,
        descuento: 50,
        precioInflado: 37.50,
        descripcion: 'Set de 6 figuras de Lilo y Stitch - 2 cm.',
        palabrasClave: 'Lilo y Stitch, Disney, set, 6 figuras, mini',
        categoria: 'Lilo y Stitch',
        pagina: 116,
        stock: 3,
        esSet: true,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872501/LS_SET_116.png'
    },
    {
        id: 'LS_SET_117',
        sku: 'LS_SET_117',
        nombre: 'SET 12 FIGURAS LILO Y STITCH',
        tamaño: '2-3 cm',
        precioOferta: 39,
        descuento: 20,
        precioInflado: 46.80,
        descripcion: 'Set de 12 figuras de Lilo y Stitch - 2 a 3 cm.',
        palabrasClave: 'Lilo y Stitch, set, 12 figuras, miniaturas',
        categoria: 'Lilo y Stitch',
        pagina: 117,
        stock: 3,
        esSet: true,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872504/LS_SET_117.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872471/LS_SET_117_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872452/LS_SET_117_2.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872433/LS_SET_117_3.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872407/LS_SET_117_4.png'
    },
    {
        id: 'DN_FIG_118',
        sku: 'DN_FIG_118',
        nombre: 'RYUK DEATH NOTE',
        tamaño: '24 cm',
        precioOferta: 39,
        descuento: 30,
        precioInflado: 50.70,
        descripcion: 'Figura de Ryuk de Death Note - 24 cm.',
        palabrasClave: 'Death Note, Ryuk, figura, shinigami',
        categoria: 'Death Note',
        pagina: 118,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872407/DN_FIG_118.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872406/DN_FIG_118_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872407/DN_FIG_118_2.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872406/DN_FIG_118_3.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872406/DN_FIG_118_4.png'
    },
    {
        id: 'SW_FIG_119',
        sku: 'SW_FIG_119',
        nombre: 'DARTH VADER ARTICULABLE',
        tamaño: '10 cm',
        precioOferta: 30,
        descuento: 40,
        precioInflado: 42.00,
        descripcion: 'Figura articulable de Darth Vader de Star Wars - 10 cm.',
        palabrasClave: 'Star Wars, Darth Vader, figura, articulable',
        categoria: 'Star Wars',
        pagina: 119,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872405/SW_FIG_119.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872405/SW_FIG_119_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872405/SW_FIG_119_3.png'
    },
    {
        id: 'SM_FIG_120',
        sku: 'SM_FIG_120',
        nombre: 'SAILOR MOON',
        tamaño: '16 cm',
        precioOferta: 35,
        descuento: 50,
        precioInflado: 52.50,
        descripcion: 'Figura de Sailor Moon - 16 cm.',
        palabrasClave: 'Sailor Moon, figura, anime, magical girl',
        categoria: 'Sailor Moon',
        pagina: 120,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872405/SM_FIG_120.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872405/SM_FIG_120_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872404/SM_FIG_120_2.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872404/SM_FIG_120_3.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872403/SM_FIG_120_4.png'
    },
    {
        id: 'SM_FIG_121',
        sku: 'SM_FIG_121',
        nombre: 'SAILOR MOON',
        tamaño: '16 cm',
        precioOferta: 35,
        descuento: 20,
        precioInflado: 42.00,
        descripcion: 'Figura de Sailor Moon - 16 cm.',
        palabrasClave: 'Sailor Moon, figura, colección',
        categoria: 'Sailor Moon',
        pagina: 121,
        stock: 3,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872404/SM_FIG_121.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872403/SM_FIG_121_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872404/SM_FIG_121_2.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872407/SM_FIG_121_3.png'
    },
    {
        id: 'SF_SET_122',
        sku: 'SF_SET_122',
        nombre: 'STREET FIGHTER',
        tamaño: '9 cm',
        precioOferta: 39,
        descuento: 30,
        precioInflado: 50.70,
        descripcion: 'Set de figuras de Street Fighter - 9 cm.',
        palabrasClave: 'Street Fighter, set, figuras, Ryu, Chun-Li',
        categoria: 'Street Fighter',
        pagina: 122,
        stock: 3,
        esSet: true,
        imagenes: 'https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872402/SF_SET_122_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872402/SF_SET_122_1.png, https://res.cloudinary.com/dwjiqcuin/image/upload/v1772872360/SF_SET_122_2.png'
    }
];

// ============================================
// FUNCIONES DE UTILIDAD
// ============================================
function obtenerCategorias() {
    const categorias = [...new Set(productos.map(p => p.categoria))];
    return categorias.sort();
}

function obtenerProductosPorCategoria(categoria) {
    if (categoria === 'todos') return productos;
    return productos.filter(p => p.categoria === categoria);
}

function buscarProductos(termino) {
    const busqueda = termino.toLowerCase();
    return productos.filter(p => 
        p.nombre.toLowerCase().includes(busqueda) ||
        p.sku.toLowerCase().includes(busqueda) ||
        p.categoria.toLowerCase().includes(busqueda) ||
        (p.palabrasClave && p.palabrasClave.toLowerCase().includes(busqueda))
    );
}

// Exportar para usar en otros archivos (si es necesario)
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { 
        productos, 
        obtenerCategorias, 
        obtenerProductosPorCategoria, 
        buscarProductos
    };
}

